version: "3.9"
services:
  api:
    # image: localai/localai:v2.11.0-aio-cpu
    # For Nvidia GPUs decomment one of the following (cuda11 or cuda12):
    # image: localai/localai:v2.11.0-aio-gpu-cuda-11
    # image: localai/localai:v2.11.0-aio-gpu-cuda-12
    image: localai/localai:v2.11.0-cublas-cuda12-ffmpeg
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 1m
      timeout: 20m
      retries: 5
    ports:
      - 8080:8080
    environment:
      - DEBUG=true
      # ...
    volumes:
      - ./models:/build/models:cached
    # decomment the following piece if running with Nvidia GPUs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
